In a gameshow, contestants try to guess which of 3 closed doors contain a cash prize (goats are behind the other two doors). Of course, the odds of choosing the correct door are 1 in 3. As a twist, the host of the show occasionally opens a door after a contestant makes his or her choice. This door is always one of the two the contestant did not pick, and is also always one of the goat doors (note that it is always possible to do this, since there are two goat doors). At this point, the contestant has the option of keeping his or her original choice, or swtiching to the other unopened door. The question is: is there any benefit to switching doors? The answer surprises many people who haven't heard the question before.

We can answer the problem by running simulations in Python. We'll do it in several parts.

In [1]:
import numpy as np

In [2]:
"""
Function
--------
simulate_prizedoor

Generate a random array of 0s, 1s, and 2s, representing
hiding a prize between door 0, door 1, and door 2

Parameters
----------
nsim : int
    The number of simulations to run

Returns
-------
sims : array
    Random array of 0s, 1s, and 2s

Example
-------
>>> print simulate_prizedoor(3)
array([0, 0, 2])
"""
def simulate_prizedoor(nsim):
    answer = np.random.randint(3, size=nsim) 
    return answer

print( simulate_prizedoor(3)) 

[0 0 2]


In [3]:
"""
Function
--------
simulate_guess

Return any strategy for guessing which door a prize is behind. This
could be a random strategy, one that always guesses 2, whatever.

Parameters
----------
nsim : int
    The number of simulations to generate guesses for

Returns
-------
guesses : array
    An array of guesses. Each guess is a 0, 1, or 2

Example
-------
>>> print simulate_guess(5)
array([0, 0, 0, 0, 0])
"""

def simulate_guess(nsim):
    guess = np.random.randint(3, size=nsim)
    return guess
print (simulate_guess(3))

[0 0 0]


In [4]:
"""
Function
--------
goat_door

Simulate the opening of a "goat door" that doesn't contain the prize,
and is different from the contestants guess

Parameters
----------
prizedoors : array
    The door that the prize is behind in each simulation
guesses : array
    THe door that the contestant guessed in each simulation

Returns
-------
goats : array
    The goat door that is opened for each simulation. Each item is 0, 1, or 2, and is different
    from both prizedoors and guesses

Examples
--------
>>> print goat_door(np.array([0, 1, 2]), np.array([1, 1, 1]))
>>> array([2, 2, 0])
"""

def goat_door(prizedoors, guesses):
    result = []
    s = 0+1+2
    for i,j in zip(prizedoors, guesses):
        if i==j:
            result.append(s-i)
        else:
            result.append(s-i-j)
    return np.array(result) 

In [5]:
print (goat_door(np.array([0, 1, 2]), np.array([1, 1, 1]))) 

[2 2 0]


In [7]:
"""
Function
--------
switch_guess

The strategy that always switches a guess after the goat door is opened

Parameters
----------
guesses : array
     Array of original guesses, for each simulation
goatdoors : array
     Array of revealed goat doors for each simulation

Returns
-------
The new door after switching. Should be different from both guesses and goatdoors

Examples
--------
>>> print switch_guess(np.array([0, 1, 2]), np.array([1, 2, 1]))
>>> array([2, 0, 0])
"""
def switch_guess(guesses, goatdoors):
    result = []
    s = 0+1+2
    for i,j in zip(goatdoors, guesses):
        if i==j:
            result.append(s-i)
        else:
            result.append(s-i-j)
    return np.array(result) 

In [9]:
print (switch_guess( np.array([0, 1, 2]), np.array([1, 2, 1])))

[2 0 0]


In [20]:
"""
Function
--------
win_percentage

Calculate the percent of times that a simulation of guesses is correct

Parameters
-----------
guesses : array
    Guesses for each simulation
prizedoors : array
    Location of prize for each simulation

Returns
--------
percentage : number between 0 and 100
    The win percentage

Examples
---------
>>> print win_percentage(np.array([0, 1, 2]), np.array([0, 0, 0]))
33.333
"""
def win_percentage(guesses, prizedoors):
    wins = (guesses == prizedoors).sum()
    return (wins/guesses.size) * 100

In [21]:
print (win_percentage(np.array([0, 1, 2]), np.array([0, 0, 0])))

33.33333333333333


In [25]:
nsim = 10000

#keep guesses
print ("Win percentage when keeping original door")
print (win_percentage(simulate_prizedoor(nsim), simulate_guess(nsim)))

#switch
pd = simulate_prizedoor(nsim)
guess = simulate_guess(nsim)
goats = goat_door(pd, guess) 
guess = switch_guess(guess, goats)
print ("Win percentage when switching doors")
print (win_percentage(pd, guess) ) 

Win percentage when keeping original door
33.47
Win percentage when switching doors
78.55
